#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$ROOT/.porkbun-deploy}"

build_surface() {
  local surface="$1"
  echo "==> Building $surface"
  (cd "$ROOT/$surface" && npm ci && npm run build)
}

copy_tree() {
  local src="$1"
  local dest="$2"
  if [[ ! -d "$src" ]]; then
    echo "Missing source directory: $src" >&2
    exit 1
  fi
  mkdir -p "$dest"
  cp -a "$src"/. "$dest"/
}

write_redirect() {
  local dest="$1"
  local target="$2"
  local title="$3"
  mkdir -p "$dest"
  cp "$ROOT/shared/command-glass.css" "$dest/command-glass.css"
  cat > "$dest/index.html" <<HTML
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="refresh" content="0; url=$target">
    <link rel="canonical" href="$target">
    <link rel="stylesheet" href="/command-glass.css">
    <style>
      .utility-shell {
        display: block;
        max-width: 760px;
      }

      .utility-panel {
        margin: 0 auto;
      }

      .utility-panel .cg-command span {
        min-width: 0;
        overflow-wrap: anywhere;
      }
    </style>
    <title>$title</title>
  </head>
  <body>
    <main class="cg-shell utility-shell">
      <section class="cg-main">
        <div class="cg-panel utility-panel">
          <div class="cg-kicker">redirect / artifacts</div>
          <h1>Opening artifacts</h1>
          <p>Redirecting to the canonical work index.</p>
          <a class="cg-command" href="$target"><span>\$ continue</span><span>$target</span></a>
        </div>
      </section>
    </main>
  </body>
</html>
HTML
}

require_index() {
  local dir="$1"
  if [[ ! -f "$dir/index.html" ]]; then
    echo "Missing index.html in $dir" >&2
    exit 1
  fi
}

echo "==> Cleaning deploy tree: $OUT"
rm -rf "$OUT"
mkdir -p "$OUT"

build_surface public-root
build_surface lab
build_surface notes
build_surface signal

echo "==> Assembling Porkbun deploy tree"
copy_tree "$ROOT/public-root/dist" "$OUT"
copy_tree "$ROOT/lab/dist" "$OUT/lab"
copy_tree "$ROOT/notes/dist" "$OUT/wiki"
copy_tree "$ROOT/signal/dist" "$OUT/signal"

copy_tree "$ROOT/links" "$OUT/links"
copy_tree "$ROOT/now" "$OUT/now"
copy_tree "$ROOT/contact" "$OUT/contact"
# Resume is provided by public-root/dist/resume — do not overwrite with static redirect.
copy_tree "$ROOT/this" "$OUT/this"
copy_tree "$ROOT/scratch" "$OUT/scratch"
copy_tree "$ROOT/ops" "$OUT/ops"
copy_tree "$ROOT/store" "$OUT/store"

# Keep deploy branch to web-serving artifacts only.
find "$OUT" -name 'package.json' -o -name 'package-lock.json' -o -name 'npm-shrinkwrap.json' | while read -r metadata_file; do
  rm -f "$metadata_file"
done

# Porkbun subdomain artifacts.hellointernet.lol maps to /artifacts.
# Current canonical artifact list lives at https://hellointernet.lol/work/ in public-root.
# Keep this as a redirect until/unless artifacts gets its own dedicated surface.
write_redirect "$OUT/artifacts" "https://hellointernet.lol/work/" "Artifacts — hellointernet.lol"

# Minimal marker for humans inspecting the generated branch.
cat > "$OUT/README.txt" <<'TXT'
Generated static artifact branch for Porkbun Static Hosting.

Source branch: main
Generated by: scripts/build-porkbun-deploy-tree.sh

Porkbun folder mappings:
- root domain -> /
- artifacts -> /artifacts
- lab -> /lab
- signal -> /signal
- wiki -> /wiki
- links -> /links
- now -> /now
- contact -> /contact
- resume -> /resume
- this -> /this
- scratch -> /scratch
- ops -> /ops
- store -> /store

Do not edit this branch by hand. Edit source files on main.
TXT

for dir in \
  "$OUT" \
  "$OUT/artifacts" \
  "$OUT/lab" \
  "$OUT/signal" \
  "$OUT/wiki" \
  "$OUT/links" \
  "$OUT/now" \
  "$OUT/contact" \
  "$OUT/resume" \
  "$OUT/this" \
  "$OUT/scratch" \
  "$OUT/ops" \
  "$OUT/store"; do
  require_index "$dir"
done

echo "==> Deploy tree ready: $OUT"
find "$OUT" -maxdepth 2 -type f | sed "s#^$OUT/##" | sort
